[package]
name = "utils_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[dependencies]
js-sys = "0.3.61"
getrandom = { version = "0.2", features = ["js"] }
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.158", features = ["derive"] }
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.61", features = ["Storage", "Window", "console"] }
yew = { version = "0.20.0", features = ["csr"] }
